a=input("enter a number ")
print(a)
b=input("Enter your name :-")
print(b)
c=input("enter a number =")
d=input("enter the second number =")
print(c+d)
print(int(c)+int(d))
e=input("enter a name=")
print(int(c)+str(e)) 